name: test-actor-A

on:
  pull_request_review:
    types: [submitted]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: actorを出力
        run: |
          echo "actor:            ${{ github.actor }}"
          echo "triggering_actor: ${{ github.triggering_actor }}"
          echo "event_name:       ${{ github.event_name }}"
